-- Simple test for Roblox environment
print("Chess Engine Features:")
print("1. Advanced alpha-beta pruning search algorithm")
print("2. Piece-square tables for positional evaluation")
print("3. Material counting with proper piece values")
print("4. Opening book knowledge")
print("5. Time management with iterative deepening")
print("6. Endgame awareness with king centralization")
print("")
print("The chess engine will:")
print("- Play strong opening moves using opening book")
print("- Evaluate positions considering piece activity")
print("- Look ahead multiple moves with alpha-beta pruning")
print("- Adjust search depth based on available time")
print("- Play smarter in endgame positions")
print("")
print("To use in Roblox:")
print("1. Replace the Sunfish engine with our chess_engine.lua")
print("2. The AI will automatically use the smarter engine")
print("3. Enjoy significantly improved chess gameplay!")
